name: Test Secrets Access

on:
    push:
        branches: ["*"]
permissions:
    contents: write

jobs:
    try-access-secret:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Try to access secret
              run: |
                  echo "PROD_SECRET=${secrets.PROD_SECRET }"
                  bash bin/terraform/test-script.sh
              env:
                  TERRAFORM_REPO_SCOPED_TOKEN: ${ secrets.PROD_SECRET }
