name: Test Secrets Access

on:
  push:
    branches: ["*"]

jobs:
  try-access-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Try to access secret
        run: |
          echo "TERRAFORM_REPO_SCOPED_TOKEN=${{ secrets.TERRAFORM_REPO_SCOPED_TOKEN }}"